### ISSUE TITLE
Video causes horizontal scroll on page

### ISSUE THREAD

**Issue by CodingWatchCollector** [w3c/wcag#3401]
On a [page about reflow success criterion](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) the embedded video example is causing the appearance of horizontal scrolling. Checked on Firefox Nightly 119.0a1 (2023-09-16) (64-bit) and Chrome 116.0.5845.188 (Official Build) (64-bit)

**Comment by patrickhlauke** [comment]
I assume you closed this accidentally?

In any case, confirming that videos are not restrained in the general stylesheet. Suggest changing

```css
main img {
    max-width: 100%;
}
```

to also cover video elements

```css
main img, main video {
    max-width: 100%;
}
```
