### ISSUE TITLE
Do user interface control labels count as part of the control for the purposes of Contrast Requirement exemptions for disabled controls?

### ISSUE THREAD

**Issue by tigt** [w3c/wcag#567]
We’re implementing a design system at my job, and we’re unsure if dimming the `<label>` associated with a disabled `<input>` is a violation or not:

```html
<input id="w" type="checkbox"> <label for="w">Checkbox label</label>
```

```css
input:disabled,
input:disabled + label {
  opacity: 0.4; /* Or color:gray or whatever */
}
```

I looked at existing UI guidelines from Apple and Microsoft, but they don’t seem to mention this case.

Our team is unsure if the [WCAG Guidelines for SC 1.4.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html) are for or against, depending on if a label is considered “part of an inactive user interface component” or not.
